#!/bin/bash

if [ $# -eq 0 ]
then
	echo "usage";
	exit 1;
elif [ "${1}" = "module" -a "${2}" ]
then
	docker-compose run api python manage.py startapp $2;
	exit 1;
elif [ "${1}" = "dev" -o "${1}" = "prod" ]
then
	docker-compose down;
	docker-compose up -d;
fi
